
supportedtypes:
        - name: pascalvoc
          format: xml
          use: imagedetectclassify
        - name: vatic
          format: xml
          use: imagedetectclassify

schemas:
    location: schemas